webtalk_init -webtalk_dir C:/Users/Alejandro/SED/Trabajo_v11/Trabajo_v1.sim/top_test/behav/xsim/xsim.dir/TOP_TB_behav/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Sat Jun 26 20:30:32 2021" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2020.2 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "3064766" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "WIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "b448bd52-6fdf-4366-b0df-0d44c74eb8fc" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "bfbceb3aab6b4c17b4193274c0caa0b5" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "7" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Windows Server 2016 or Windows 10" -context "user_environment"
webtalk_add_data -client project -key os_release -value "major release  (build 9200)" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "AMD A12-9720P RADEON R7, 12 COMPUTE CORES 4C+8G" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "2695 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "12.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key Command -value "xsim" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key trace_waveform -value "true" -context "xsim\\usage"
webtalk_add_data -client xsim -key runtime -value "12014375 us" -context "xsim\\usage"
webtalk_add_data -client xsim -key iteration -value "0" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Time -value "0.25_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Memory -value "12300_KB" -context "xsim\\usage"
webtalk_transmit -clientid 4009514350 -regid "" -xml C:/Users/Alejandro/SED/Trabajo_v11/Trabajo_v1.sim/top_test/behav/xsim/xsim.dir/TOP_TB_behav/webtalk/usage_statistics_ext_xsim.xml -html C:/Users/Alejandro/SED/Trabajo_v11/Trabajo_v1.sim/top_test/behav/xsim/xsim.dir/TOP_TB_behav/webtalk/usage_statistics_ext_xsim.html -wdm C:/Users/Alejandro/SED/Trabajo_v11/Trabajo_v1.sim/top_test/behav/xsim/xsim.dir/TOP_TB_behav/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
